import type { Metadata } from "next";
import { Geist, Geist_Mono,Black_Han_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import QueryProvider from "./QueryProvider";
import NavBar from "@/components/NavBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const blackHanSans = Black_Han_Sans({
  weight: [ '400'],
  variable:"--font-black-han-sans",
  subsets: ["latin"],
  display: 'swap'
})
const montserrat = Montserrat({
  weight: [ '400','500','100','200','600','700','800'],
  variable:"--font-black-han-sans",
  subsets: ["latin"],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${blackHanSans.variable} antialiased bg-stone-400`}
      >
        <StoreProvider >
          <QueryProvider>
            <NavBar/>
            {children}
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
